name: Delete Old Releases and Tags

on:
  push:

jobs:
  delete_old_releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g gh
      - run: |
          # Logic to get latest release
          latest_release=$(gh release list --limit 1 | jq -r '.[0].tagName')

          # Logic to delete older releases and tags
          gh release list --limit 100 | tail -n +2 | while read release; do
            tag_name=$(echo "$release" | cut -d' ' -f3)
            gh release delete "$release"
            gh tag delete "$tag_name"
          done
