name: Delete Old Releases and Tags

on:
  push:

jobs:
  delete_old_releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sgpublic/delete-release-action@v1.1
        with:
          # repo: '<owner>/<repoName>'  # Optional, defaults to current repo
          release-drop: true
          release-keep-count: 1
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
