name: Download SharePoint File

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Set up PowerShell environment
        run: |
          # Set Execution Policy
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force

          # Install the PackageManagement module if not present
          if (-not (Get-Module -ListAvailable -Name PackageManagement)) {
            Install-Module -Name PackageManagement -Force -AllowClobber
          }

          # Install the NuGet provider
          # Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Verbose

          # Force the installation of NuGet in case it's not available
          if (-not (Get-PackageProvider -Name NuGet)) {
            Install-PackageProvider -Name NuGet -Force -Verbose
          }

          # Install the SharePoint Online PnP PowerShell module
          Install-Module -Name SharePointPnPPowerShellOnline -Force -AllowClobber -Verbose

      - name: Download SharePoint Client SDK
        run: |
          # Download the SharePoint Online Client SDK
          $url = "https://download.microsoft.com/download/6/D/7/6D7E26D8-C96B-4858-9DCE-6B40B9A3C0B9/SharePointOnlineClientComponents_16.0.23011.12000.zip"
          $zipPath = "$env:TEMP\SharePointOnlineClientComponents.zip"
          Invoke-WebRequest -Uri $url -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath "$env:TEMP\SharePointOnlineClientComponents"

      - name: Add SharePoint CSOM Assemblies and Download File
        run: |
          $csomPath = "$env:TEMP\SharePointOnlineClientComponents\Microsoft.SharePoint.Client.dll"
          $runtimePath = "$env:TEMP\SharePointOnlineClientComponents\Microsoft.SharePoint.Client.Runtime.dll"

          Add-Type -Path $csomPath
          Add-Type -Path $runtimePath

          $siteUrl = "https://sysforetech-my.sharepoint.com/"
          $documentUrl = "https://sysforetech-my.sharepoint.com/:t:/g/personal/shalini_s_sysfore_com/EZpRZocmbnhCjz-ZiG_RIsIBhArpEjEglx6APwQ0Tr5f_g?e=kJpf4m"
          $downloadPath = "C:\_temp\Updates.ps1"

          $securePassword = ConvertTo-SecureString "${{ secrets.SHAREPOINT_PASSWORD }}" -AsPlainText -Force
          $clientContext = New-Object Microsoft.SharePoint.Client.ClientContext($siteUrl)
          $clientContext.Credentials = New-Object Microsoft.SharePoint.Client.SharePointOnlineCredentials("${{ secrets.SHAREPOINT_USERNAME }}", $securePassword)

          $fileInfo = [Microsoft.SharePoint.Client.File]::OpenBinaryDirect($clientContext, $documentUrl)
          $fileStream = New-Object System.IO.FileStream($downloadPath, [System.IO.FileMode]::Create)
          $fileInfo.Stream.CopyTo($fileStream)

          $fileStream.Close()
          $fileStream.Dispose()

      - name: Output Download Path
        run: echo "File downloaded to C:\_temp\Updates.ps1"
