name: Release Tag Workflow

on:
  push:
    branches:
      - main

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'sys-shalini'
          git config --global user.email 'shalini.s@sysfore.com'

      - name: Create and push tag
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git tag v1.3
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git push origin v1.3
 
      - name: Determine Tag Name
        id: get_tag
        run: echo "::set-output name=tag_name::$(git describe --tags --abbrev=0)"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          release_name: ${{ steps.get_tag.outputs.tag_name }}
          body: 'Description of the release'
          draft: false
          prerelease: false