name: Tag Triggered Workflow

# on:
#   push:
#     tags:
#       - 'v*'

on: 
  release: 
    types: 
      - released
        
jobs:
  handle-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Branch name
        id: get_branch
        run: |
          BRANCH=$(git branch -r --contains ${{ github.event.release.tag_name }} | grep -v '\->' | grep -o '[^ ]*$')
          echo "branch=$BRANCH" >> $GITHUB_ENV

      - name: Print tag
        run: |
          echo "The tag is $GITHUB_REF"
          echo "Branch: ${{ env.branch }}"