name: Tag Triggered Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  handle-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print tag
        run: echo "The tag is $GITHUB_REF"
