name: Release Tag Workflow

on:
  push:
    branches:
      - main

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create and push tag
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git tag v1.0
          git push https://x-access-token:${{ secrets.PAT }}@github.com/sys-shalini/github-actions.git v1.0
