name: Release Tag Workflow

on:
  push:
    branches:
      - main

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create and push tag
        run: |
          git tag v1.0
          git push origin v1.0
